sudo: required
language: c
matrix:
  include:
    - env: ARCH_TRAVIS_ARCH="i686"
    - env: ARCH_TRAVIS_ARCH="x86_64"
arch:
  repos:
    - archlinuxcn=http://repo.archlinuxcn.org/$arch
  packages:
    - julia-git
    - cmake
    - mbedtls
    - xdelta3
  script:
    - julia -e 'Pkg.add("LibArchive"); Pkg.checkout("LibArchive")'
    - julia -e 'Pkg.clone(pwd())'
    - julia -e 'Pkg.build("LibALPM")'
    - julia --check-bounds=yes -e 'Pkg.test("LibALPM", coverage=true)'
    - julia -e 'cd(Pkg.dir("LibALPM")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
