sudo: required
language: c
arch:
  repos:
    - archlinuxcn=http://repo.archlinuxcn.org/$arch
  packages:
    - julia-git
  script:
    - julia -e 'Pkg.clone(pwd(), "LibALPM")'
    - julia -e 'Pkg.build("LibALPM")'
    - julia --check-bounds=yes -e 'Pkg.test("LibALPM", coverage=true)'
    - julia -e 'cd(Pkg.dir("LibALPM")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

script:
  - bash arch-travis.sh
