sudo: required
dist: trusty
services:
  - docker
language: c
matrix:
  include:
    - env: ARCHJL_JULIA_VERSION=0.6
    - env: ARCHJL_JULIA_VERSION=nightly
before_install:
  - (cd travis && docker build -f Dockerfile -t archjl . --build-arg JULIA_VERSION=$ARCHJL_JULIA_VERSION)
  - docker run -d --privileged -v ${PWD}:${PWD} archjl /usr/lib/systemd/systemd | sudo tee /docker-name
script:
  - sudo bash travis/runtest.sh
